repos:
- repo: local
  hooks:
    - id: lint
      name: Ruff Lint
      description: Linting using ruff
      entry: bash -c 'ruff check .'
      language: system
      stages: ["pre-commit", "pre-push"]

    - id: format
      name: Ruff Format
      description: Formatting using ruff
      entry: bash -c 'ruff format . --check'
      language: system
      stages: ["pre-commit", "pre-push"]
