# build and test some end points
name: Build and deploy docs for fmu-sumo-sim2sumo

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build_pywheels:
    name: Build docs with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and build docs
        run: |
          pip install pip -U && pip install wheel -U
          pip install .[docs]
          pip list
          sphinx-build docs build/sphinx/html
