name: Check formatting and linting

on:
  pull_request:
  push: { branches: [main] }

jobs:
  ruff-check:
    name: Run ruff lint and format checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Installing dependencies
        run: pip install ruff

      - name: Run ruff lint
        run: ruff check .

      - name: Run ruff format
        run: ruff format . --check
