name: Build and test fmu-sumo-uploader

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "5 5 * * *"

jobs:
  build_pywheels:
    name: PY ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: f96c150d-cacf-4257-9cc9-54b2c68ec4ce
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          subscription-id: 87897772-fb27-495f-ae40-486a2df57baa

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install fmu-sumo-sim2sumo
        run: >
          python -m pip install --upgrade pip &&
          python -m pip install .
          python -m pip install git+https://github.com/equinor/fmu-sumo-uploader.git@main
      - name: Run tests
        shell: bash
        run: |
          az --version
          az account list
          pip show sumo-wrapper-python
          pip show fmu-sumo-uploader
          python -c  'import sys; print(sys.platform)'
          python -c 'import os; import sys; print(os.path.dirname(sys.executable))'
          access_token=$(az account get-access-token --scope api://88d2b022-3539-4dda-9e66-853801334a86/.default --query accessToken --output tsv)
          export ACCESS_TOKEN=$access_token

          pytest -s --timeout=300
