name: Build and test fmu-sumo-sim2sumo

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "5 5 * * *"

jobs:
  build_pywheels:
    name: PY ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
      max-parallel: 1
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: f96c150d-cacf-4257-9cc9-54b2c68ec4ce
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          subscription-id: 87897772-fb27-495f-ae40-486a2df57baa

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install fmu-sumo-sim2sumo
        run: |
          python -m pip install --upgrade pip
          python -m pip install opm
          python -m pip install git+https://github.com/equinor/fmu-sumo-uploader.git@main
          python -m pip install git+https://github.com/equinor/fmu-dataio.git@main
          python -m pip install pytest
          python -m pip install pytest-timeout
          python -m pip install .
      - name: Run tests
        shell: bash
        env:
          sharedkey: ${{ secrets.SHARED_KEY_DROGON_WRITE_DEV }}
        run: |
          az --version
          az account list
          echo "Length of sharedkey variable read from Github Secrets:" ${#sharedkey}
          mkdir ~/.sumo
          echo $sharedkey > ~/.sumo/88d2b022-3539-4dda-9e66-853801334a86.sharedkey
          ls -l ~/.sumo/88d2b022-3539-4dda-9e66-853801334a86.sharedkey
          pip list | grep sumo
          python -c  'import sys; print(sys.platform)'
          python -c 'import os; import sys; print(os.path.dirname(sys.executable))'

          pytest --log-cli-level=WARNING -s --timeout=300
